[build]
   base = /opt/build/repo/Projeto
   command = npm run build
   commandOrigin = config
   publish = /opt/build/repo/Projeto/build
   publishOrigin = config

[[publish]]
 from = "/Projeto/"
 to = "/Projeto/projeto.html"
 status = 200